import type { Destination } from '../types/destination';

/** Popular Long Island Sound destinations — centered around Centerport, NY cruising grounds.
 *  Covers the North Shore of Long Island, Connecticut coast, and Block Island Sound.
 *
 *  ⚠ COORDINATES ARE APPROXIMATE — many were estimated and may be slightly off.
 *  The boat owner should verify and correct positions using the Edit feature in the app
 *  (Destinations → tap destination → Edit → tap the map to place the pin).
 *  Positions should be ON THE WATER at the dock/mooring/anchorage, not on land. */
export const LONG_ISLAND_SOUND_DESTINATIONS: Destination[] = [
  // === Centerport / Huntington area (home port) ===
  {
    id: 'lis-centerport-yc',
    name: 'Centerport Yacht Club ⚓ Home',
    type: 'yacht-club',
    position: { lat: 40.9015, lng: -73.3592 },
    region: 'new-england',
    description:
      'Home yacht club. Located on the east side of the peninsula in Northport Harbor (not Centerport Harbor, despite the name). Guest moorings, launch service, reciprocal privileges.',
    vhfChannel: '16/78',
    phone: '631-261-9770',
    amenities: {
      fuel: false, water: true, electric: false, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: false, reservationRequired: true },
    entranceControllingDepthFt: 12,
    depthSourceNote: 'Navionics, read by owner 2026-08-12',
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-huntington-yc',
    name: 'Huntington Yacht Club',
    type: 'yacht-club',
    position: { lat: 40.8963, lng: -73.4211 },
    region: 'new-england',
    description:
      'Historic yacht club on Huntington Harbor with guest moorings, launch, and full dining. Reciprocal.',
    vhfChannel: '16/78',
    phone: '631-427-4949',
    amenities: {
      fuel: false, water: true, electric: true, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: false,
      dinghyDock: true, pool: true, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: false, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-halesite-marina',
    name: 'Halesite Marina',
    type: 'marina',
    position: { lat: 40.9020, lng: -73.4230 },
    region: 'new-england',
    description: 'Full-service marina on Huntington Harbor, close to Huntington Village restaurants and shops.',
    vhfChannel: '16/09',
    phone: '631-421-0700',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: false, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 200, maxLOA: 60, maxDraft: 7, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-northport-bay-anchorage',
    name: 'Northport Bay Anchorage',
    type: 'anchorage',
    position: { lat: 40.9160, lng: -73.3560 },
    region: 'new-england',
    description: 'Large protected anchorage in Northport Bay. Good holding, plenty of swing room.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud/sand',
      protectionFrom: ['S', 'SW', 'W'],
      exposedTo: ['N', 'NE'],
      typicalDepthFeet: 12,
      maxDepthFeet: 20,
      swingRoomFeet: 200,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-northport-village-dock',
    name: 'Northport Village Dock',
    type: 'town-dock',
    position: { lat: 40.9035, lng: -73.3432 },
    region: 'new-england',
    description: 'Village dock at Northport Harbor. Walking distance to Main Street restaurants and ice cream.',
    amenities: {
      fuel: false, water: true, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: true, reservationRequired: false },
    entranceControllingDepthFt: 12,
    depthSourceNote: 'Navionics, read by owner 2026-08-12',
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-northport-yc',
    name: 'Northport Yacht Club',
    type: 'yacht-club',
    position: { lat: 40.9045, lng: -73.3445 },
    region: 'new-england',
    description: 'Northport Harbor yacht club with reciprocal privileges, moorings, and launch service.',
    vhfChannel: '16/78',
    amenities: {
      fuel: false, water: true, electric: false, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: false, reservationRequired: true },
    entranceControllingDepthFt: 12,
    depthSourceNote: 'Navionics, read by owner 2026-08-12',
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // === Oyster Bay / Cold Spring Harbor ===
  {
    id: 'lis-oyster-bay-anchorage',
    name: 'Oyster Bay Anchorage',
    type: 'anchorage',
    position: { lat: 40.8920, lng: -73.5310 },
    region: 'new-england',
    description: 'Well-protected anchorage in Oyster Bay. Good holding in mud. Near Sagamore Hill.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'excellent',
      bottomType: 'mud',
      protectionFrom: ['N', 'NE', 'E', 'S'],
      exposedTo: ['NW'],
      typicalDepthFeet: 10,
      swingRoomFeet: 250,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-seawanhaka-corinthian-yc',
    name: 'Seawanhaka Corinthian Yacht Club',
    type: 'yacht-club',
    position: { lat: 40.8945, lng: -73.5240 },
    region: 'new-england',
    description: 'Historic yacht club on Centre Island in Oyster Bay. Founded 1871. Reciprocal privileges.',
    vhfChannel: '16/78',
    phone: '516-922-6200',
    amenities: {
      fuel: false, water: true, electric: false, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: false, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-cold-spring-harbor-anchorage',
    name: 'Cold Spring Harbor',
    type: 'anchorage',
    position: { lat: 40.8820, lng: -73.4650 },
    region: 'new-england',
    description: 'Scenic anchorage in Cold Spring Harbor. Historic village with whaling museum.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud',
      protectionFrom: ['S', 'SW', 'SE'],
      exposedTo: ['N', 'NW'],
      typicalDepthFeet: 12,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // === Port Jefferson area ===
  {
    id: 'lis-port-jefferson-harbor',
    name: 'Port Jefferson Harbor',
    type: 'anchorage',
    position: { lat: 40.9534, lng: -73.0750 },
    region: 'new-england',
    description:
      'Large, protected harbor in Port Jefferson. Popular with transients. Good restaurants in town. Ferry traffic — watch for wakes.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud',
      protectionFrom: ['N', 'NE', 'E', 'S', 'SW'],
      exposedTo: [],
      typicalDepthFeet: 15,
      swingRoomFeet: 300,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-danfords-marina',
    name: 'Danford\'s Hotel & Marina',
    type: 'marina',
    position: { lat: 40.9522, lng: -73.0714 },
    region: 'new-england',
    description: 'Full-service marina and hotel in Port Jefferson Harbor. Pool, restaurants, walking distance to village.',
    vhfChannel: '16/09',
    phone: '631-928-5200',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: false, repairs: false,
      dinghyDock: true, pool: true, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 100, maxLOA: 200, maxDraft: 10, pricePerFoot: 5.50, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // === Greenport / Shelter Island / East End ===
  {
    id: 'lis-greenport-mitchell-park',
    name: 'Mitchell Park Marina (Greenport)',
    type: 'marina',
    position: { lat: 41.1035, lng: -72.3620 },
    region: 'new-england',
    description:
      'Village-operated marina in downtown Greenport. Walking distance to everything. Restored 1920s carousel adjacent.',
    vhfChannel: '16/09',
    phone: '631-477-2200',
    amenities: {
      fuel: false, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 50, maxLOA: 200, pricePerFoot: 4.75, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-dering-harbor',
    name: 'Dering Harbor (Shelter Island)',
    type: 'mooring',
    position: { lat: 41.0928, lng: -72.3484 },
    region: 'new-england',
    description: 'Protected mooring field off Shelter Island. Quiet, scenic, near Shelter Island Yacht Club.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'mooring',
      mooringCount: 20,
      pricePerNight: 50,
      maxLOA: 50,
      dinghyDock: true,
      launchService: false,
      reservationRequired: false,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-sag-harbor',
    name: 'Sag Harbor',
    type: 'marina',
    position: { lat: 40.9986, lng: -72.2930 },
    region: 'new-england',
    description:
      'Historic whaling village and trendy Hamptons destination. Municipal moorings + several marinas. Expect crowds in summer.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', maxLOA: 150, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-block-island-great-salt-pond',
    name: 'Block Island — Great Salt Pond',
    type: 'anchorage',
    position: { lat: 41.1883, lng: -71.5800 },
    region: 'new-england',
    description:
      'Famous Block Island anchorage and mooring field. One of the best cruising destinations in New England. Dinghy to Old Harbor for restaurants, shops, and beaches.',
    vhfChannel: '16/68',
    amenities: {
      fuel: true, water: true, electric: false, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'excellent',
      bottomType: 'sand/mud',
      protectionFrom: ['N', 'NE', 'E', 'S', 'SW', 'W', 'NW'],
      exposedTo: [],
      typicalDepthFeet: 15,
      swingRoomFeet: 200,
      maxBoats: 500,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // === Connecticut coast ===
  {
    id: 'lis-mystic-seaport',
    name: 'Mystic Seaport Marina',
    type: 'marina',
    position: { lat: 41.3644, lng: -71.9669 },
    region: 'new-england',
    description:
      'Marina at Mystic Seaport Museum. Walking distance to downtown Mystic, restaurants, and the famous pizza.',
    vhfChannel: '16/09',
    phone: '860-572-5391',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: false, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 60, maxLOA: 100, pricePerFoot: 5.00, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-essex-ct',
    name: 'Essex, CT (Connecticut River)',
    type: 'marina',
    position: { lat: 41.3534, lng: -72.3887 },
    region: 'new-england',
    description:
      'Charming historic village on the Connecticut River. Essex Yacht Club and several marinas. Classic New England cruising.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-stamford-yc',
    name: 'Stamford Yacht Club',
    type: 'yacht-club',
    position: { lat: 41.0314, lng: -73.5386 },
    region: 'new-england',
    description: 'Well-regarded yacht club on Stamford Harbor. Reciprocal privileges, moorings, launch service.',
    vhfChannel: '16/78',
    phone: '203-323-3161',
    amenities: {
      fuel: false, water: true, electric: false, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: false,
      dinghyDock: true, pool: true, ice: true, propane: false,
    },
    details: { type: 'marina', transientSlips: false, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-norwalk-cove',
    name: 'Norwalk Cove Marina',
    type: 'marina',
    position: { lat: 41.0683, lng: -73.4003 },
    region: 'new-england',
    description: 'Large full-service marina in East Norwalk. Restaurant, pool, walking to Norwalk.',
    vhfChannel: '16/09',
    phone: '203-838-5899',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: false, repairs: true,
      dinghyDock: true, pool: true, ice: true, propane: true,
    },
    details: { type: 'marina', slipCount: 450, maxLOA: 100, maxDraft: 8, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-new-haven-yacht-haven',
    name: 'New Haven (Morris Cove Anchorage)',
    type: 'anchorage',
    position: { lat: 41.2581, lng: -72.8836 },
    region: 'new-england',
    description: 'Protected anchorage in Morris Cove, New Haven harbor. Good holding.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: false, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud',
      protectionFrom: ['N', 'NE', 'NW', 'W'],
      exposedTo: ['S', 'SE'],
      typicalDepthFeet: 15,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-milford-ct',
    name: 'Milford Landing Marina',
    type: 'marina',
    position: { lat: 41.2194, lng: -73.0527 },
    region: 'new-england',
    description: 'Town-operated marina in Milford Harbor, CT. Walking distance to downtown Milford.',
    vhfChannel: '16/09',
    phone: '203-874-1610',
    amenities: {
      fuel: false, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 58, maxLOA: 65, pricePerFoot: 3.50, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // === Mid-LI Sound bailout harbors (Long Island north shore) ===
  {
    id: 'lis-mt-sinai-harbor',
    name: 'Mt Sinai Harbor',
    type: 'anchorage',
    position: { lat: 40.9608, lng: -73.0200 },
    region: 'new-england',
    description: 'Protected harbor just east of Port Jefferson. Narrow entrance but good refuge once inside. Popular bailout for LI Sound transits.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud',
      protectionFrom: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
      exposedTo: [],
      typicalDepthFeet: 10,
    },
    entranceControllingDepthFt: 7,
    depthSourceNote: 'Navionics, read by owner 2026-08-12',
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-mattituck-inlet',
    name: 'Mattituck Inlet',
    type: 'anchorage',
    position: { lat: 41.0195, lng: -72.5570 },
    region: 'new-england',
    description: 'Long Island north shore refuge. Narrow inlet — watch depths and current. Mattituck Creek extends 1.5 NM inland with anchoring and a town dock.',
    amenities: {
      fuel: true, water: true, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud',
      protectionFrom: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
      exposedTo: [],
      typicalDepthFeet: 8,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-orient-harbor',
    name: 'Orient Harbor',
    type: 'anchorage',
    position: { lat: 41.1360, lng: -72.3065 },
    region: 'new-england',
    description: 'Well-protected anchorage at the tip of the North Fork. Quiet and scenic, good holding.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'sand/mud',
      protectionFrom: ['N', 'NE', 'E', 'W', 'NW'],
      exposedTo: ['S', 'SW'],
      typicalDepthFeet: 12,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-montauk-lake',
    name: 'Lake Montauk',
    type: 'marina',
    position: { lat: 41.0740, lng: -71.9350 },
    region: 'new-england',
    description: 'Montauk Harbor — deep, protected, easy entrance. Multiple marinas, restaurants, fuel. The main refuge for the east end of Long Island.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: true,
    },
    details: { type: 'marina', slipCount: 200, maxLOA: 100, maxDraft: 10, transientSlips: true, reservationRequired: false },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // === Connecticut coast mid-trip bailouts ===
  {
    id: 'lis-bridgeport-harbor',
    name: 'Bridgeport Harbor',
    type: 'marina',
    position: { lat: 41.1790, lng: -73.1930 },
    region: 'new-england',
    description: 'Large protected harbor on CT coast. Several marinas, fuel available. Not pretty but a reliable refuge.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 150, maxLOA: 80, maxDraft: 10, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-branford-harbor',
    name: 'Branford Harbor',
    type: 'mooring',
    position: { lat: 41.2545, lng: -72.8070 },
    region: 'new-england',
    description: 'Sheltered harbor on CT coast east of New Haven. Branford Yacht Club and several marinas. Good bailout.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: false, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: {
      type: 'mooring',
      mooringCount: 30,
      pricePerNight: 40,
      maxLOA: 55,
      dinghyDock: true,
      launchService: true,
      reservationRequired: false,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-guilford-harbor',
    name: 'Guilford Harbor',
    type: 'marina',
    position: { lat: 41.2600, lng: -72.6670 },
    region: 'new-england',
    description: 'Guilford Yacht Club and town facilities. Shallow entrance — check tide. Pretty CT coastal village.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 40, maxLOA: 55, maxDraft: 6, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-clinton-harbor',
    name: 'Clinton Harbor',
    type: 'marina',
    position: { lat: 41.2630, lng: -72.5380 },
    region: 'new-england',
    description: 'Clinton Harbor on the CT coast. Cedar Island Marina and several others. Protected inside.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: true,
      dinghyDock: true, pool: true, ice: true, propane: false,
    },
    details: { type: 'marina', slipCount: 300, maxLOA: 100, maxDraft: 8, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-saybrook-point',
    name: 'Saybrook Point (Connecticut River)',
    type: 'marina',
    position: { lat: 41.2830, lng: -72.3500 },
    region: 'new-england',
    description: 'Mouth of the Connecticut River — excellent refuge from LI Sound weather. Multiple marinas, full services.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: true,
      dinghyDock: true, pool: true, ice: true, propane: true,
    },
    details: { type: 'marina', slipCount: 200, maxLOA: 150, maxDraft: 10, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-niantic-bay',
    name: 'Niantic Bay',
    type: 'anchorage',
    position: { lat: 41.3100, lng: -72.1900 },
    region: 'new-england',
    description: 'Protected bay on the CT coast. Good holding, moorings available from local clubs.',
    amenities: {
      fuel: false, water: false, electric: false, pumpout: false, showers: false,
      laundry: false, wifi: false, restaurant: false, groceries: false, repairs: false,
      dinghyDock: true, pool: false, ice: false, propane: false,
    },
    details: {
      type: 'anchorage',
      holdingQuality: 'good',
      bottomType: 'mud',
      protectionFrom: ['N', 'NE', 'E', 'NW'],
      exposedTo: ['S', 'SW'],
      typicalDepthFeet: 15,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-new-london-harbor',
    name: 'New London Harbor',
    type: 'marina',
    position: { lat: 41.3550, lng: -72.0830 },
    region: 'new-england',
    description: 'Thames River mouth — large, deep, very well-protected. Ferry traffic (watch wakes). Multiple marinas, full services.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: true, pumpout: true, showers: true,
      laundry: true, wifi: true, restaurant: true, groceries: true, repairs: true,
      dinghyDock: true, pool: false, ice: true, propane: true,
    },
    details: { type: 'marina', slipCount: 300, maxLOA: 200, maxDraft: 12, transientSlips: true, reservationRequired: true },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lis-stonington-harbor',
    name: 'Stonington Harbor',
    type: 'mooring',
    position: { lat: 41.3375, lng: -71.9050 },
    region: 'new-england',
    description: 'Historic CT village with well-protected harbor. Moorings available, walking distance to restaurants.',
    vhfChannel: '16/09',
    amenities: {
      fuel: true, water: true, electric: false, pumpout: true, showers: true,
      laundry: false, wifi: true, restaurant: true, groceries: true, repairs: false,
      dinghyDock: true, pool: false, ice: true, propane: false,
    },
    details: {
      type: 'mooring',
      mooringCount: 25,
      pricePerNight: 45,
      maxLOA: 50,
      dinghyDock: true,
      launchService: true,
      reservationRequired: false,
    },
    reviews: [],
    isUserAdded: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
