import type { Route } from '../../../types/navigation';
import { format } from 'date-fns';

/** Format a route as a PredictWind-compatible text summary.
 *  PredictWind doesn't have a public API, but accepts pasted route summaries
 *  via their "Saved Routes" feature. This formats the route so a user can
 *  paste it into the PredictWind app for cross-reference.
 *
 *  Output includes:
 *    - Route name and description
 *    - Each waypoint with decimal degrees (PredictWind format)
 *    - Distance, estimated time, fuel
 *    - GPX-compatible coordinates for drag-and-drop
 */
export function formatRouteForPredictWind(route: Route): string {
  const lines: string[] = [];

  lines.push(`=== ${route.name} ===`);
  if (route.description) lines.push(route.description);
  lines.push('');

  lines.push(`Distance: ${route.totalDistanceNM.toFixed(1)} NM`);
  lines.push(`Est. time: ${route.totalEstimatedTimeHours.toFixed(1)} hrs at ${route.expectedSpeedKnots} kt`);
  lines.push(`Est. fuel: ${route.totalEstimatedFuelGallons.toFixed(1)} gal`);
  lines.push(`Created: ${format(new Date(route.createdAt), 'yyyy-MM-dd HH:mm')}`);
  lines.push('');

  lines.push('Waypoints:');
  route.waypoints.forEach((wp, i) => {
    const latStr = `${Math.abs(wp.position.lat).toFixed(5)}°${wp.position.lat >= 0 ? 'N' : 'S'}`;
    const lngStr = `${Math.abs(wp.position.lng).toFixed(5)}°${wp.position.lng >= 0 ? 'E' : 'W'}`;
    lines.push(`  ${i + 1}. ${wp.name}`);
    lines.push(`     ${latStr}, ${lngStr}`);
    lines.push(`     (${wp.position.lat.toFixed(5)}, ${wp.position.lng.toFixed(5)})`);
    if (wp.notes) lines.push(`     Notes: ${wp.notes}`);
  });
  lines.push('');

  if (route.legs.length > 0) {
    lines.push('Legs:');
    route.legs.forEach((leg, i) => {
      const from = route.waypoints[i]?.name ?? `WP${i + 1}`;
      const to = route.waypoints[i + 1]?.name ?? `WP${i + 2}`;
      lines.push(
        `  ${from} → ${to}: ${leg.distanceNM.toFixed(1)} NM, ` +
          `${Math.round(leg.bearingMagnetic).toString().padStart(3, '0')}°M, ` +
          `${leg.estimatedTimeHours.toFixed(1)}h, ${leg.estimatedFuelGallons.toFixed(1)}g`
      );
    });
    lines.push('');
  }

  lines.push('--- To import into PredictWind ---');
  lines.push('1. Open PredictWind app/website');
  lines.push('2. Create new route');
  lines.push('3. Enter waypoints from the list above (copy lat,lng pairs)');
  lines.push('4. Or use GPX export from this tool and drag into PredictWind Offshore');
  lines.push('');
  lines.push('Generated by Cruising Planner');

  return lines.join('\n');
}

/** Copy formatted route text to the clipboard */
export async function copyRouteToClipboard(route: Route): Promise<void> {
  const text = formatRouteForPredictWind(route);
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
  } else {
    // Fallback: use a hidden textarea
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
  }
}

/** Download route as a .txt file (useful for sharing via email/text) */
export function downloadRouteAsText(route: Route): void {
  const text = formatRouteForPredictWind(route);
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${route.name.replace(/[^a-z0-9]/gi, '_')}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
